name: Android Continuous Integration
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read
      checks: write

    steps:
      - name: Setup
        uses: actions/checkout@v4.1.7

      - name: Setup JDK
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0
        id: setup-gradle
        with:
          gradle-version: 8.7

      - name: Run Tests
        uses: ./.github/actions/run-tests

      - name: Summarize Reports
        uses: ./.github/actions/reports